# where to save your prediect result
save_dir: eval_result/

tasks:
    Anomalous_Event_Attribution:
        type: text
        data_path: datasets/Anomalous_Event_Attribution.jsonl
        compare_func:
            path: benchmark_code/BizFinBench/eval_AEA.py
    Financial_Time_Reasoning:
        type: text
        data_path: datasets/Financial_Time_Reasoning.jsonl
        compare_func:
            path: benchmark_code/BizFinBench/eval_financial_timereason.py
    Financial_Named_Entity_Recognition:
        type: text
        data_path: datasets/Financial_Named_Entity_Recognition.jsonl
        compare_func:
            path: benchmark_code/BizFinBench/eval_fin_ner.py
    Financial_Numerical_Computation:
        type: text
        data_path: datasets/Financial_Numerical_Computation.jsonl
        compare_func:
            path: benchmark_code/BizFinBench/eval_financial_calculation.py
    Emotion_Recognition:
        type: text
        data_path: datasets/Emotion_Recognition.jsonl
        compare_func:
            path: benchmark_code/BizFinBench/eval_financial_sentiment.py
    Stock_Price_Prediction:
        type: text
        data_path: datasets/Stock_Price_Prediction.jsonl
        compare_func:
            path: benchmark_code/BizFinBench/eval_stock_prediction.py
